### ISSUE TITLE
Console spam and items use

### ISSUE THREAD

**Issue by TugaPowerROM** [renzuzu/renzu_status#1]
When use bread or water it have no effect over the status, think the issue its form renzu_status, also have a huge spam client side relative to basic needs and renzu_hud , altough the renzu_hud maybe its normal, but should consider reduce the spam it gives client side. Using latest ESX Legacy.

![imagem](https://user-images.githubusercontent.com/9769460/130322132-ab9a4026-b806-484c-80ad-5a7b10eb33ff.png)

**Comment by renzuzu** [comment]
Download the latest update 
And also esx status is now usable with renzu hud

And the dummy prints for hud is a skinchanger
Are you not using skinchanger

**Comment by TugaPowerROM** [comment]
No, was using fivem-appearence that replaces skinchanger and esx_skin ( this 2 are removed from server ) , dont need to use renzu_status ? Renzu_hud support esx_status now ?

**Comment by renzuzu** [comment]
Yes esx status is supported

I will make a patch to support fivem appearance

**Comment by TugaPowerROM** [comment]
fivem-appearence for me it was a no go since breake must of the clothing stuff, swaped to cui_character!
